DROP DATABASE IF EXISTS courseservice;
DROP USER IF EXISTS 'course_service'@'%';
CREATE DATABASE IF NOT EXISTS courseservice CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'course_service'@'%' IDENTIFIED WITH mysql_native_password BY 'password';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON studentservice.* TO 'course_service'@'%';